#ifndef __INI_CONV_INIT_H_
#define __INI_CONV_INIT_H_

/**
 *************************************************
 */
 #include "ini_conv.h"
///要转换的所有节点key的表格
static const conv_ini_t conv_ini_all[] = {
			{NO_ACCORD2_A, IS_S_ONLY, "leave_fac:year", "leave_fac:year", "leave_fac:year", "leave_fac:year"},
			{NO_ACCORD2_A, IS_S_ONLY, "leave_fac:mon", "leave_fac:mon", "leave_fac:mon", "leave_fac:mon"},
			{NO_ACCORD2_A, IS_S_ONLY, "leave_fac:day", "leave_fac:day", "leave_fac:day", "leave_fac:day"},
			{NO_ACCORD2_A, IS_S_ONLY, "leave_fac:hour", "leave_fac:hour", "leave_fac:hour", "leave_fac:hour"},
			{NO_ACCORD2_A, IS_S_ONLY, "leave_fac:min", "leave_fac:min", "leave_fac:min", "leave_fac:min"},
			{NO_ACCORD2_A, IS_S_ONLY, "leave_fac:sec", "leave_fac:sec", "leave_fac:sec", "leave_fac:sec"},
			{NO_ACCORD2_A, IS_S_ONLY, "leave_fac:date", "leave_fac:date", "leave_fac:date", "leave_fac:date"},
			
			{NO_ACCORD2_A, IS_S_ONLY, "product:local_update", "product:local_update", "product:local_update", "product:local_update"},
			{NO_ACCORD2_A, IS_S_ONLY, "product:watch_interval", "product:watch_interval", "product:watch_interval", "product:watch_interval"},
			{NO_ACCORD2_A, IS_S_ONLY, "product:inst_ack", "product:inst_ack", "product:inst_ack", "product:inst_ack"},
			{NO_ACCORD2_A, IS_S_ONLY, "product:reset_modem", "product:reset_modem", "product:reset_modem", "product:reset_modem"},
			{NO_ACCORD2_A, IS_S_ONLY, "product:reset_modem_time", "product:reset_modem_time", "product:reset_modem_time", "product:reset_modem_time"},
			{NO_ACCORD2_A, IS_S_ONLY, "product:auto_unlock_time", "product:auto_unlock_time", "product:auto_unlock_time", "product:auto_unlock_time"},
			
			//{NO_ACCORD2_A, IS_S_ONLY, "alarmversion:version", "alarmversion:version", "alarmversion:version", "alarmversion:version"},
			
			{NO_ACCORD2_A, IS_S_ONLY, "resource:disk_capacity", "resource:disk_capacity", "resource:disk_capacity", "resource:disk_capacity"},

			{NO_ACCORD2_A, IS_S_ONLY, "devinfo:devguid", "devinfo_dev2:devguid", "devinfo:devguid", "devinfo:devguid"},
			{NO_ACCORD2_A, IS_S_ONLY, "devinfo:devtype", "devinfo:devtype", "devinfo:devtype", "devinfo:devtype"},
			{NO_ACCORD2_A, IS_S_ONLY, "devinfo:devtypestring","devinfo:devtypestring", "devinfo:devtypestring", "devinfo:devtypestring"},
			{NO_ACCORD2_A, IS_S_ONLY, "devinfo:batchseq","devinfo:batchseq", "devinfo:batchseq", "devinfo:batchseq"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "devinfo:firmware","devinfo:firmware", "devinfo:firmware", "devinfo:firmware"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "devinfo:cur_time","devinfo:cur_time", "devinfo:cur_time", "devinfo:cur_time"},

		
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:internet_mode", "net_config:internet_mode", "net_config:internet_mode", "net_config:internet_mode"},
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:use_dhcp", "net_config:use_dhcp", "net_config:use_dhcp", "net_config:use_dhcp"},
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:use_upnp", "net_config:use_upnp", "net_config:use_upnp", "net_config:use_upnp"},
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:adsl_user", "net_config:adsl_user", "net_config:adsl_user", "net_config:adsl_user"},
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:adsl_passwd", "net_config:adsl_passwd", "net_config:adsl_passwd", "net_config:adsl_passwd"},
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:route_mac_bind", "net_config:route_mac_bind", "net_config:route_mac_bind", "net_config:route_mac_bind"},
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:route_mac", "net_config:route_mac", "net_config:route_mac", "net_config:route_mac"},
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:route_default", "net_config:route_default", "net_config:route_default", "net_config:route_default"},
			{IS_ACCORD2_A, NOT_S_ONLY, "net_config:dns_server", "net_config:dns_server", "net_config:dns_server", "net_config:dns_server"},
			
			{IS_ACCORD2_A, NOT_S_ONLY, "port:cmd_port", "port_dev2:cmd_port", "port:cmd_port", "port:cmd_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:image_port", "port_dev2:image_port", "port:image_port", "port:image_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:audio_port", "port_dev2:audio_port", "port:audio_port", "port:audio_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:com0_port", "port_dev2:com0_port", "port:com0_port", "port:com0_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:com1_port", "port_dev2:com1_port", "port:com1_port", "port:com1_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:ftp_port", "port_dev2:ftp_port", "port:ftp_port", "port:ftp_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:pasv_min_port", "port_dev2:pasv_min_port", "port:pasv_min_port", "port:pasv_min_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:pasv_max_port", "port_dev2:pasv_max_port", "port:pasv_max_port", "port:pasv_max_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:telnet_port", "port_dev2:telnet_port", "port:telnet_port", "port:telnet_port"},
			{IS_ACCORD2_A, NOT_S_ONLY, "port:web_port", "port_dev2:web_port", "port:web_port", "port:web_port"},
		
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm:snap_pic_path", NULL, "alarm:snap_pic_path", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm:snap_pic_num", NULL, "alarm:snap_pic_num", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm:snap_pic_interval", NULL, "alarm:snap_pic_interval", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm:trig_in", NULL, "alarm:trig_in", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm:tin_mask", NULL, "alarm:tin_mask", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm:alarm_out", NULL, "alarm:alarm_out", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm:alarm_mask", NULL, "alarm:alarm_mask", NULL},
			
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:0", NULL, "actiondefine:0", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:1", NULL, "actiondefine:1", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:2", NULL, "actiondefine:2", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:3", NULL, "actiondefine:3", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:4", NULL, "actiondefine:4", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:5", NULL, "actiondefine:5", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:6", NULL, "actiondefine:6", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:7", NULL, "actiondefine:7", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:8", NULL, "actiondefine:8", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:30", NULL, "actiondefine:30", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:31", NULL, "actiondefine:31", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:32", NULL, "actiondefine:32", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:33", NULL, "actiondefine:33", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:34", NULL, "actiondefine:34", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:40", NULL, "actiondefine:40", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:51", NULL, "actiondefine:51", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:52", NULL, "actiondefine:52", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:53", NULL, "actiondefine:53", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:54", NULL, "actiondefine:54", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:55", NULL, "actiondefine:55", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:56", NULL, "actiondefine:56", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:57", NULL, "actiondefine:57", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "actiondefine:58", NULL, "actiondefine:58", NULL},
		
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:alarmtype", NULL, "alarm0:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:attrib", NULL, "alarm0:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:enable", NULL, "alarm0:enable", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:trigcode", NULL, "alarm0:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:setalarm", NULL, "alarm0:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:operid", NULL, "alarm0:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:operid", NULL, "alarm0:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:imact", NULL, "alarm0:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:ackact", NULL, "alarm0:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:selectact", NULL, "alarm0:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm0:rstact", NULL, "alarm0:rstact", NULL},
			
			
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:alarmtype", NULL, "alarm1:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:attrib", NULL, "alarm1:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:enable", NULL, "alarm1:enable", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:trigcode", NULL, "alarm1:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:setalarm", NULL, "alarm1:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:operid", NULL, "alarm1:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:operid", NULL, "alarm1:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:imact", NULL, "alarm1:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:ackact", NULL, "alarm1:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:selectact", NULL, "alarm1:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm1:rstact", NULL, "alarm1:rstact", NULL},
			
			
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:alarmtype", NULL, "alarm2:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:attrib", NULL, "alarm2:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:enable", NULL, "alarm2:enable", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:trigcode", NULL, "alarm2:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:setalarm", NULL, "alarm2:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:operid", NULL, "alarm2:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:operid", NULL, "alarm2:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:imact", NULL, "alarm2:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:ackact", NULL, "alarm2:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:selectact", NULL, "alarm2:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm2:rstact", NULL, "alarm2:rstact", NULL},
			
			
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:alarmtype", NULL, "alarm3:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:attrib", NULL, "alarm3:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:enable", NULL, "alarm3:enable", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:trigcode", NULL, "alarm3:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:setalarm", NULL, "alarm3:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:operid", NULL, "alarm3:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:operid", NULL, "alarm3:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:imact", NULL, "alarm3:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:ackact", NULL, "alarm3:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:selectact", NULL, "alarm3:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm3:rstact", NULL, "alarm3:rstact", NULL},
			
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:alarmtype", NULL, "alarm4:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:attrib", NULL, "alarm4:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:enable", NULL, "alarm4:enable", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:trigcode", NULL, "alarm4:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:setalarm", NULL, "alarm4:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:operid", NULL, "alarm4:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:operid", NULL, "alarm4:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:imact", NULL, "alarm4:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:ackact", NULL, "alarm4:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:selectact", NULL, "alarm4:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm4:rstact", NULL, "alarm4:rstact", NULL},
			
			
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:alarmtype", NULL, "alarm5:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:attrib", NULL, "alarm5:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:enable", NULL, "alarm5:enable", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:trigcode", NULL, "alarm5:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:setalarm", NULL, "alarm5:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:operid", NULL, "alarm5:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:operid", NULL, "alarm5:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:imact", NULL, "alarm5:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:ackact", NULL, "alarm5:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:selectact", NULL, "alarm5:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm5:rstact", NULL, "alarm5:rstact", NULL},
			
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:alarmtype", NULL, "alarm6:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:attrib", NULL, "alarm6:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:enable", NULL, "alarm6:enable", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:trigcode", NULL, "alarm6:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:setalarm", NULL, "alarm6:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:operid", NULL, "alarm6:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:operid", NULL, "alarm6:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:imact", NULL, "alarm6:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:ackact", NULL, "alarm6:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:selectact", NULL, "alarm6:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm6:rstact", NULL, "alarm6:rstact", NULL},
			
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:alarmtype", NULL, "alarm7:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:attrib", NULL, "alarm7:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:enable", NULL, "alarm7:enable", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:trigcode", NULL, "alarm7:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:setalarm", NULL, "alarm7:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:operid", NULL, "alarm7:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:imact", NULL, "alarm7:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:ackact", NULL, "alarm7:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:selectact", NULL, "alarm7:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "alarm7:rstact", NULL, "alarm7:rstact", NULL},
			
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:alarmtype", NULL, "motion0:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:attrib", NULL, "motion0:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:trigcode", NULL, "motion0:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:setalarm", NULL, "motion0:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:operid", NULL, "motion0:operid", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:imact", NULL, "motion0:imact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:ackact", NULL, "motion0:ackact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:selectact", NULL, "motion0:selectact", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion0:rstact", NULL, "motion0:rstact", NULL},
			
			
			{NO_ACCORD2_A, NOT_S_ONLY, "motion1:alarmtype", NULL, "motion1:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion1:attrib", NULL, "motion1:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion1:trigcode", NULL, "motion1:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion1:setalarm", NULL, "motion1:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion1:operid", NULL, "motion1:operid", NULL},

			{NO_ACCORD2_A, NOT_S_ONLY, "motion2:alarmtype", NULL, "motion2:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion2:attrib", NULL, "motion2:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion2:trigcode", NULL, "motion2:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion2:setalarm", NULL, "motion2:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion2:operid", NULL, "motion2:operid", NULL},

			{NO_ACCORD2_A, NOT_S_ONLY, "motion3:alarmtype", NULL, "motion3:alarmtype", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion3:attrib", NULL, "motion3:attrib", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion3:trigcode", NULL, "motion3:trigcode", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion3:setalarm", NULL, "motion3:setalarm", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "motion3:operid", NULL, "motion3:operid", NULL},
		
			{NO_ACCORD2_A, NOT_S_ONLY, "install:inst_place", "install_dev2:inst_place", "install:inst_place", "install:inst_place"},
			{NO_ACCORD2_A, NOT_S_ONLY, "install:inst_place_enable", "install_dev2:inst_place_enable", "install:inst_place_enable", "install:inst_place_enable"},
			{NO_ACCORD2_A, NOT_S_ONLY, "install:inst_place_posx", "install_dev2:inst_place_posx", "install:inst_place_posx", "install:inst_place_posx"},
			{NO_ACCORD2_A, NOT_S_ONLY, "install:inst_place_posy", "install_dev2:inst_place_posy", "install:inst_place_posy", "install:inst_place_posy"},
			{NO_ACCORD2_A, NOT_S_ONLY, "install:osd_max_len", "install_dev2:osd_max_len", "install:osd_max_len", "install:osd_max_len"},

			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:videostandlist", "hqenc0:videostandlist", "hqenc0:videostandlist", "hqenc0:videostandlist"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:videostand", "hqenc0:videostand", "hqenc0:videostand", "hqenc0:videostand"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:encodingtype", "hqenc0:encodingtype", "hqenc0:encodingtype", "hqenc0:encodingtype"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:audencmode", "hqenc0:audencmode", "hqenc0:audencmode", "hqenc0:audencmode"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:vidpicsize", "hqenc0:vidpicsize", "hqenc0:vidpicsize", "hqenc0:vidpicsize"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:picenctype", "hqenc0:picenctype", "hqenc0:picenctype", "hqenc0:picenctype"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:framerate", "hqenc0:framerate", "hqenc0:framerate", "hqenc0:framerate"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:bitratecon", "hqenc0:bitratecon", "hqenc0:bitratecon", "hqenc0:bitratecon"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:targetbitrate", "hqenc0:targetbitrate", "hqenc0:targetbitrate", "hqenc0:targetbitrate"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:minbitrate", "hqenc0:minbitrate", "hqenc0:minbitrate", "hqenc0:minbitrate"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:maxbitrate", "hqenc0:maxbitrate", "hqenc0:maxbitrate", "hqenc0:maxbitrate"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:quant", "hqenc0:quant", "hqenc0:quant", "hqenc0:quant"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:iinterval", "hqenc0:iinterval", "hqenc0:iinterval", "hqenc0:iinterval"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:timeout", "hqenc0:timeout", "hqenc0:timeout", "hqenc0:timeout"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:th_drop", "hqenc0:th_drop", "hqenc0:th_drop", "hqenc0:th_drop"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:th_dropvideo", "hqenc0:th_dropvideo", "hqenc0:th_dropvideo", "hqenc0:th_dropvideo"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:mic_vol", "hqenc0:mic_vol", "hqenc0:mic_vol", "hqenc0:mic_vol"},
			//{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:audio_vol", "hqenc0:audio_vol", "hqenc0:audio_vol", "hqenc0:audio_vol"},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:mic_vol", NULL, "netencoder:mic_vol", NULL},
			{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:audio_vol", NULL, "netencoder:audio_vol", NULL},
			
			//{NO_ACCORD2_A, NOT_S_ONLY, "netencoder:net_ch", "hqenc0:net_ch", "hqenc0:net_ch", "hqenc0:net_ch"},
			
			{IS_ACCORD2_A, NOT_S_ONLY, "eth0:ipaddr", "eth0:ipaddr", "eth0:ipaddr", "eth0:ipaddr"},
			{IS_ACCORD2_A, NOT_S_ONLY, "eth0:netmask", "eth0:netmask", "eth0:netmask", "eth0:netmask"},
			{IS_ACCORD2_A, NOT_S_ONLY, "eth0:mac_addr", "eth0:mac_addr", "eth0:mac_addr", "eth0:mac_addr"},
			
			{NO_ACCORD2_A, NOT_S_ONLY, "hqpara:rec_ch", "hqpara1:rec_ch", "hqpara:rec_ch", "hqpara:rec_ch"},
			{NO_ACCORD2_A, NOT_S_ONLY, "hqpara:follow_net", "hqpara1:follow_net", "hqpara:follow_net", "hqpara:follow_net"},
			{NO_ACCORD2_A, NOT_S_ONLY, "hqpara:pre_rec", "hqpara1:pre_rec", "hqpara:pre_rec", "hqpara:pre_rec"},
			{NO_ACCORD2_A, NOT_S_ONLY, "hqpara:dly_rec", "hqpara1:dly_rec", "hqpara:dly_rec", "hqpara:dly_rec"},
			{NO_ACCORD2_A, NOT_S_ONLY, "hqpara:cut_len", "hqpara1:cut_len", "hqpara:cut_len", "hqpara:cut_len"},
			{NO_ACCORD2_A, NOT_S_ONLY, "hqpara:del_typ", "hqpara1:del_typ", "hqpara:del_typ", "hqpara:del_typ"},
			{NO_ACCORD2_A, NOT_S_ONLY, "hqpara:rec_type", "hqpara1:rec_type", "hqpara:rec_type", "hqpara:rec_type"},
	
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:name", "video1:name", "video0:name", "video0:name"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:enable", "video1:enable", "video0:enable", "video0:enable"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:bright", "video1:bright", "video0:bright", "video0:bright"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:color", "video1:color", "video0:color", "video0:color"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:contrast", "video1:contrast", "video0:contrast", "video0:contrast"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:saturation", "video1:saturation", "video0:saturation", "video0:saturation"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:blind_sen", "video1:blind_sen", "video0:blind_sen", "video0:blind_sen"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:blind_alarm_time", "video1:blind_alarm_time", "video0:blind_alarm_time", "video0:blind_alarm_time"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:blind_cancelalarm_time", "video1:blind_cancelalarm_time", "video0:blind_cancelalarm_time", "video0:blind_cancelalarm_time"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:motion_sen", "video1:motion_sen", "video0:motion_sen", "video0:motion_sen"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:motion_alarm", "video1:motion_alarm", "video0:motion_alarm", "video0:motion_alarm"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area0", "video1:area0", "video0:area0", "video0:area0"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area1", "video1:area1", "video0:area1", "video0:area1"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area2", "video1:area2", "video0:area2", "video0:area2"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area3", "video1:area3", "video0:area3", "video0:area3"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area4", "video1:area4", "video0:area4", "video0:area4"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area5", "video1:area5", "video0:area5", "video0:area5"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area6", "video1:area6", "video0:area6", "video0:area6"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area7", "video1:area7", "video0:area7", "video0:area7"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area8", "video1:area8", "video0:area8", "video0:area8"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area9", "video1:area9", "video0:area9", "video0:area9"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area10", "video1:area10", "video0:area10", "video0:area10"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:area11", "video1:area11", "video0:area11", "video0:area11"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:starthour", "video1:starthour", "video0:starthour", "video0:starthour"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:startmin", "video1:startmin", "video0:startmin", "video0:startmin"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:endhour", "video1:endhour", "video0:endhour", "video0:endhour"},
			{NO_ACCORD2_A, NOT_S_ONLY, "video0:endmin", "video1:endmin", "video0:endmin", "video0:endmin"},
			
			{NO_ACCORD2_A, NOT_S_ONLY, "remote_gate:rmt_gate_num", "remote_gate_dev2:rmt_gate_num", "remote_gate:rmt_gate_num", "remote_gate:rmt_gate_num"},
			{NO_ACCORD2_A, NOT_S_ONLY, "remote_gate:rmt_gate1", "remote_gate_dev2:rmt_gate1", "remote_gate:rmt_gate1", "remote_gate:rmt_gate1"},
			{NO_ACCORD2_A, NOT_S_ONLY, "remote_gate:rmt_gate2", "remote_gate_dev2:rmt_gate2", "remote_gate:rmt_gate2", "remote_gate:rmt_gate2"},
			{NO_ACCORD2_A, NOT_S_ONLY, "remote_gate:rmt_gate3", "remote_gate_dev2:rmt_gate3", "remote_gate:rmt_gate3", "remote_gate:rmt_gate3"},
			{NO_ACCORD2_A, NOT_S_ONLY, "remote_gate:alarm_gate", "remote_gate_dev2:alarm_gate", "remote_gate:alarm_gate", "remote_gate:alarm_gate"},
			{NO_ACCORD2_A, NOT_S_ONLY, "remote_gate:env", "remote_gate_dev2:env", "remote_gate:env", "remote_gate:env"},
			{NO_ACCORD2_A, NOT_S_ONLY, "remote_gate:enc", "remote_gate_dev2:enc", "remote_gate:enc", "remote_gate:enc"},

//2011.03.31   zsk 增加对于gps信息gps:band gps:enable gps:port gps:stop gps:parity gps:date的转换
			{NO_ACCORD2_A, NOT_S_ONLY, "gps:baud", NULL, "gps:baud", "gps:baud"}, 
			{NO_ACCORD2_A, NOT_S_ONLY, "gps:enable", NULL, "gps:enable", "gps:enable"},
			{NO_ACCORD2_A, NOT_S_ONLY, "gps:stop", NULL, "gps:stop", "gps:stop"},
			{NO_ACCORD2_A, NOT_S_ONLY, "gps:port", NULL, "gps:port", "gps:port"},
			{NO_ACCORD2_A, NOT_S_ONLY, "gps:parity", NULL, "gps:parity", "gps:parity"},
			{NO_ACCORD2_A, NOT_S_ONLY, "gps:date", NULL, "gps:date", "gps:date"}
};
 
///在转换前需要进行特殊处理的节点key列表
static const conv_spcial_t conv_spcial[] = {
	{"devinfo:devguid", "devinfo_dev2:devguid", "devinfo:devguid", "devinfo:devguid"},
	{"port:cmd_port", "port_dev2:cmd_port", "port:cmd_port", "port:cmd_port"},
	{"port:com0_port", "port_dev2:com0_port", "port:com0_port", "port:com0_port"},
	{"port:com1_port", "port_dev2:com1_port", "port:com1_port", "port:com1_port"},
	{"port:image_port", "port_dev2:image_port", "port:image_port", "port:image_port"},
	{"port:audio_port", "port_dev2:audio_port", "port:audio_port", "port:audio_port"},
	{"port:ftp_port", "port_dev2:ftp_port", "port:ftp_port", "port:ftp_port"},
	{"port:pasv_min_port", "port_dev2:pasv_min_port", "port:pasv_min_port", "port:pasv_min_port"},
	{"port:pasv_max_port", "port_dev2:pasv_max_port", "port:pasv_max_port", "port:pasv_max_port"},
	{"port:telnet_port", "port_dev2:telnet_port", "port:telnet_port", "port:telnet_port"},
	{"port:web_port", "port_dev2:web_port", "port:web_port", "port:web_port"}
};

#endif 
